connect-foundation/2019-20

.gitignore
.prettierignore
.prettierrc.js
commitlint.config.js
lerna.json
package.json
yarn.lock

-  린터 및 프리티어에 대한 설정을 완료했습니다.
- 협업을 함에 있어 공통된 형식을 사용하기 위해 린터와 프리티어에 대한 설정을 진행하였습니다.
- 동기에 대한 내용은 [issue 10](https://github.com/connect-foundation/2019-20/issues/10)에 자세히 있습니다.
- 설정 방법에 대한 설정은  [wiki](https://github.com/connect-foundation/2019-20/wiki/Linter&Prettier)에 기록하였습니다.
- 기본 환경 설정으로 테스트는 없습니다.
Closes #10

ESLint & Prettier 세팅

---

.github/workflows/client-object-storage-nCloud.yml
.github/workflows/react-build-test.yml
.github/workflows/server-api-deploy.yml
.github/workflows/server-api-test.yml

-  CI/CD를 위한 기본 github actions 설정을 완료하였습니다.
- 웹 프로젝트를 진행하면서 local 작업후 server로 전달하는 과정이 번거롭기 때문에 이를 자동화하여 처리하기 위해 github actions 설정을 진행하였습니다.
- 다른 도구(nCloud, Jenkins)를 사용하지 않고 github actions을 사용하는 이유는 다음과 같습니다.
- travis ci 도구와 유사
- github을 사용하므로 해당 도구를 보다 많은 활용이 가능할 것이라는 생각
- nCloud는 AWS로 대체해서 사용할 수 있으므로, nCloud와 연동하기 위해 aws 자료를 참고 가능
- docker 관련 설정은 다음에 하자는 팀원의 의견에 따라 docker를 이용한 배포가 아닌방법을 이용하여 처리하였습니다.
- 기본 환경 설정이므로 별도의 테스트는 없으며, 임의의 저장소르 통해 동작됨을 확인했습니다.
- 실제 사용시 다시 한번 테스트가 필요합니다.
- 다음 스크린샷은 예시일 뿐이며, 동작을 위해서는 다음과 같은 과정이 필요하며 보다 세부적인 사항은 [wiki 내용 참조](https://github.com/connect-foundation/2019-20/wiki/github-actions-%EC%84%A4%EC%A0%95) 바랍니다.
-  package.json에 다음과 같은 항목이 추가되어야합니다.
`"test":"jest"`
- 서버에는 다음과 같은 패키지가 설치되어야 합니다.
`pm2`
- 서버에는 다음과 같은 스크립트가 포함되어 있어야 합니다.
```bash
BRANCHNAME=$2
if [ …
```

CI/CD를 위한 기초 github actions 설정

---

.eslintignore
apis/template/README.md
apis/template/app.js
apis/template/bin/www
apis/template/package.json
apis/template/routes/index.js
yarn.lock

프로젝트 전반에 걸쳐 사용가능한 하나의 예시 템플릿을 작성하였습니다 
프로젝트를 진행하며 여러대의 API 서버가 생성되고, 그 과정에서 동일한 폴더 구조를 갖기 위해서 생성하였습니다. 
이 템플릿을 사용시, 중앙의 `lerner` 을 통해 package가 관리되고, commit시마다 linter를 검증하게 됩니다.
현재는 기본적인 방법으로 express generator를 통하여 생성되었고, 미래에는 하나의 패키지로서 template을 제거하는 방법으로 진행될 예정입니다. 
issue #5 에 구체적인 동기에 대한 설명이 포함되어 있습니다. 
기능 개발이 아닌 템플릿으로서 테스트를 포함하지 않습니다.
Closes #5

공통으로 사용할 ExpressJS template 생성

---

.github/workflows/react-build-test.yml

- github actions에서 기존 server api test를 재활용하던 코드에서 수정하지 못한 부분(제목) 수정
- 기존 server api test가 react build and test와 제목이 중복되어 actions에 표시되지않는 문제가 발생하여 수정합니다.
- 환경설정이므로 테스트는 없습니다.
Closes #9

github actions 에서 name이 겹쳐서 표시되지 않는 문제 수정

---

.prettierrc.js
apis/template/package.json
lerna.json
package.json

prettier에서 사용되는 탭의 크기를 tab에서 space로 변경
- 2칸임에도 Tab으로 들여쓰기를 하게 되면, 가독성을 해칩니다.
- yarn fix 명령어를 통하여 새로운 기준을 일괄 적용 하였습니다.
테스트 코드를 포함하지 않습니다.

refactor: change and apply indent unit from tab to space

---

.github/workflows/client-object-storage-nCloud.yml
.github/workflows/react-build-test.yml
.github/workflows/server-api-deploy.yml
.github/workflows/server-api-test.yml

- 기존에 작성했던 workflows가 현재 프로젝트의 폴더 구조를 전혀 반영되어 있지 않아서 이 환경에 맞게 수정하였습니다.
- 기능 수정에 따라 환경변수 관련 설정파일을 자동으로 암호화하는 과정이 필요할 수 있습니다.
- client react의 build, test와 express에서의 build, test가 올바른지 검토해주시면 됩니다. (test, build 과정에 외부 입력을 받기 위해 대기 하는 과정이 없다고 가정하여 작성하였습니다.)
- 기존 작성한 방법으로는 정상적으로 빌드 및 테스트가 진행되지 않는 문제가 있습니다.
- 규칙에 따라 express에서 CommonJS에서 ES6로 변경함에 따라 바벨 컴파일을 사용하기 때문에 빌드 테스트 과정이 필요하다 판단되어 해당 항목을 추가하였습니다.
- 서비스 기능 개발시 필요에 의하여 중요하지만 외부에 공개하기 어려운 정보를 저장해야할 필요성이 있기 때문에 공개키/개인키(비대칭키)를 통해 암호화하여 데이터를 전달하는 항목을 추가하였습니다.
- 서비스에 따라 데이터베이스, nginx등의 설정이 필요할 수 있는데 하나의 서버에 처리를 하거나 별도의 서버를 두어 처리하는 방법이 달라질 수 있기 때문에 각각의 설정방법은 workflows에서 직접 설정하지 않고 각각의 서비스에서 처리하도록 하였습니다.
- 별다른 툴을 사용하지 않고 실제 프로젝트와 최대한 동일한 환경을 유지하기 위하여 현재 저장소를 fork 하고, nCloud Object Storage와 서버를 통해 직접 확인하였습니다.
Closes #9

프로젝트에 환경(폴더 구조)에 따라 정상적으로 CI/CD가 가능하도록 수정

---

apis/template/.babelrc
apis/template/app.js
apis/template/package.json
yarn.lock

- babel 세팅에 대한 오류 사항이 있어 이를 수정합니다.
- 과거 바벨 세팅중 로컬에서의 전역 노드 모듈과 섞여 설정에서 빠진 부분이 있어 이를 수정 및 브라우저 호환성에서 수정이 필요한 부분이 있어서 이에 대한 추가사항입니다.
- 라우터를 임시로 async await이 필요한 형태로 수정하여 브라우저에서 잘 동작하는 것을 확인하였습니다.

HOTFIX : change babel setting

---

web-apps/client/src/App.js
web-apps/client/src/components/card/content-section.js
web-apps/client/src/components/card/index.js
web-apps/client/src/components/inline-items.js
web-apps/client/src/components/list-view.js
web-apps/client/src/components/pretto-slider.js
web-apps/client/src/components/tap-page.js
web-apps/client/src/contexts/user.js
web-apps/client/src/index.css
web-apps/client/src/pages/main/index.js
web-apps/client/src/pages/my-article-list.js
web-apps/client/src/pages/mypage.js
web-apps/client/src/service/product.js

- 사용자가 작성한 글을 조회하거나, 사용자의 평판을 확인할 수 있습니다.
- 사용자가 작성한 글을 조회하거나 사용자의 평판을 확인할 수 있고 위치정볼를 조정할수 있는 페이지입니다.
- X
Closes #84

작성한 글 / 관심 목록 / 구매 목록 조회 페이지

---

apis/auth/app.js
apis/auth/assets/errorMessages.js
apis/auth/assets/uris.js
apis/auth/core/userManagement.js
apis/auth/migrations/20191205051150-create-user.js
apis/auth/models/user.js
apis/auth/package.json
apis/auth/routes/controller/errorHandler.js
apis/auth/routes/controller/loginControl.js
apis/auth/routes/controller/publicInformation.js
apis/auth/routes/index.js
apis/auth/routes/middlewares/userManagement.js
apis/auth/seeders/20191205123247-demo-user.js
apis/auth/tests/index.test.js
apis/auth/utils/corsOptions.js
apis/auth/utils/index.js

- auth api 변동 및 수정사항에 대한 PR 입니다.
- 유저 추가시 post credential 요청에 대해 redirect가 cors policy에 의해 제한 된 이슈를 해결하였습니다.
- 판매자의 정보를 받아오기 위한 api를 추가하였습니다.
- 탈퇴 api 추가하였습니다.
- 회원 ID  uuid로 변경하였습니다.
- supertest를 이용하여 테스트코드를 작성하였습니다.

Auth api- 네아로 구현

---

web-apps/client/src/assets/errorMessages.js
web-apps/client/src/assets/messages.js
web-apps/client/src/assets/productDescriptionField.js
web-apps/client/src/components/ProductDescription.jsx
web-apps/client/src/components/SellerInfo.jsx
web-apps/client/src/contexts/AlertMessage.jsx
web-apps/client/src/contexts/User.jsx
web-apps/client/src/pages/ProductDetail.jsx
web-apps/client/src/utils/index.js
web-apps/client/src/utils/object.js

Client web/fixerror

---

web-apps/client/src/contexts/Filters.jsx
web-apps/client/src/pages/main/index.js

- 기존 'error_message' 였던 항목을 enum으로 관리하기 때문에 해당
변경사항에 맞 변경
- 기존 'error_message' 였던 항목을 enum으로 관리하기 때문에 해당
변경사항에 맞 변경

dispatch message 의 type 변경에 따른 수정

---

web-apps/client/src/components/TwoNumberInput.jsx
web-apps/client/src/pages/filters/index.js
web-apps/client/src/pages/main/index.js

- 변수명을 변경하면서 반영되지 못한 필터 페이지 영역 수정
- 필터 페이지에서 입력길이가 길어져 두줄로 나타나는 문제 수정
- 필터 적용 오류

필터 적용 오류 수정

---

.github/workflows/client-object-storage-nCloud.yml

object storage -  배포 오타 수정

---

apis/auth/app.js
apis/auth/assets/uris.js
apis/auth/bin/www.js
apis/auth/package.json
apis/auth/utils/corsOptions.js

- production에서 타겟클라이언트 변경으로 인한 수정입니다.

production에서 타켓 클라이언트 변경

---

apis/auth/assets/uris.js

- 클라이언트 주소 잘못 지정된 것이 있어서 수정했습니다.

fix: fix client host

---

.github/workflows/react-build-test.yml
web-apps/client/src/assets/uris.js
web-apps/client/src/components/LogOutButton.jsx
web-apps/client/src/pages/MyPage.jsx
web-apps/client/src/pages/WriteProduct.jsx
web-apps/client/src/utils/apiCall.js
web-apps/client/src/utils/auth.js

- 회원탈퇴 버튼 동작 가능하게 수정 / CI 캐싱
- 회원탈퇴 버튼 동작 가능하게 수정 / CI 캐싱
(CI시 yarn을 통해 의존성 설치 속도 개선을 하기 위함 / CD인 경우 권한오류로 미지원)

회원탈퇴 버튼 동작 가능하게 수정 / CI 캐싱

---

apis/auth/routes/controller/loginControl.js
apis/auth/routes/index.js
apis/auth/tests/index.test.js

- 유저 정보 검증에서 오류로 인한  수정
- 토큰 정보를 반환해 주는 api 추가

토큰 반환 라우터 추가

---

web-apps/client/src/pages/ProductDetail.jsx

조회수 중복 방지 오류 수정
- 조회수 중복방지를 위해서 서버에서 쿠키를 체크하여 중복으로
조회수 증가되지 않게 설정
- cross-origin으로 인해서 (same-origin이 default) 쿠키 전달이 되지 않으므로
이를 해결하기 위해서 axios credentials 전달
- 기존 axios.get(uri, config)에서 config에서 credential을 추가할경우
정상적으로 동작하지 않는 문제가 있어 axios(config) 방법 사용

조회수 중복 방지 오류 수정

---

web-apps/client/src/pages/MyPage.jsx

- 평가자가 0명이면 0으로 나누게 되므로 오류가 발생하므로 중간값인 5
표시

마이페이지 출력 오류 수정(평판 출력 오류 - 평가가 없을때)

---

apis/product/app.js
apis/product/assets/uri.js
apis/product/core/callAPI.js
apis/product/package.json
apis/product/routes/middleware/cookie.js
apis/product/routes/middleware/user.js

- cors에 따른 글 수정/삭제 오류 수정 및 jwt 토큰검증을

cors에 따른 글 수정/삭제 오류 수정 및 jwt 토큰검증을

---

apis/auth/assets/uris.js
apis/auth/routes/controller/loginControl.js

- referer을 분석하여 CSRF 공격에 대비합니다.

fix: add constraint of referer

---

web-apps/client/src/components/ListView.jsx
web-apps/client/src/components/LogOutButton.jsx
web-apps/client/src/components/ProductFooter.jsx
web-apps/client/src/pages/ChatList.jsx
web-apps/client/src/service/product.js

- 예외처리 오류 수정 및 관심목록 조회 오류 수정
- 관심목록이 회원별로 출력되도록 수정
- 로그아웃 시 정상적으로 예외처리 되지 않아 발생하는 문제 해결

예외처리 오류 수정 및 관심목록 조회 오류 수정

---

apis/auth/assets/uris.js

fix: fix referer

---

web-apps/client/src/assets/uris.js

fix: fix url

---

apis/auth/assets/uris.js

fix: add referer github

---

web-apps/client/src/pages/ArticleList.jsx
web-apps/client/src/service/product.js

작성글 조회 cors 오류 수정
- 페이지를 불러올 때 쿠키가 필요하므로 수정

작성글 조회 cors 오류 수정

---

apis/auth/assets/uris.js

fix: fix referer errror

---

web-apps/client/src/service/product.js

fix: post to fix in mistake

---

web-apps/client/src/contexts/Filters.jsx

fix: lat, lon change filter

---

apis/auth/routes/controller/loginControl.js
apis/auth/tests/index.test.js

fix: fix logout problem issue

---

web-apps/client/src/utils/index.js

같은 날짜가 반복되는 문제를 해결
테스트를 포함하지 않습니다

fix: date formatting error for same day

---

apis/chat/.babelrc
apis/chat/.eslintignore
apis/chat/.eslintrc.json
apis/chat/app.js
apis/chat/bin/www.js
apis/chat/config/index.js
apis/chat/core/index.js
apis/chat/db/index.js
apis/chat/db/model/chat.js
apis/chat/db/model/index.js
apis/chat/package-lock.json
apis/chat/package.json
apis/chat/routes/controller/chat.js
apis/chat/routes/controller/index.js
apis/chat/routes/index.js
apis/chat/tests/index.test.js
yarn.lock

채팅을 위한 https & 소켓 서버를 구축하였습니다.  
socket.io, express, 그리고 mongodb를 통해 구현하였습니다.

Chat api/merge

---

apis/chat/.babelrc
apis/chat/.eslintignore
apis/chat/.eslintrc.json
apis/chat/app.js
apis/chat/bin/www.js
apis/chat/config/index.js
apis/chat/core/index.js
apis/chat/db/index.js
apis/chat/db/model/chat.js
apis/chat/db/model/index.js
apis/chat/package-lock.json
apis/chat/package.json
apis/chat/routes/controller/chat.js
apis/chat/routes/controller/index.js
apis/chat/routes/index.js
apis/chat/tests/index.test.js
yarn.lock

Chat api/master

---

web-apps/client/src/pages/ChatList.jsx

- 스크롤이 react-window의 스크롤과 중첩되어 상하로 이동되는 문제 해결

fix: adjust react-window height
